# The basic requirements for building the hosted docs
name: cl_docs

channels:
  - defaults
  - conda-forge

dependencies:
  - python
  - pip
  - git

  - pandas
  - scikit-learn
  - sparse
  - dill
  - patsy
  - statsmodels
  - matplotlib

  # Docs
  - ipython
  - parso>=0.8
  - nbsphinx
  - numpydoc

  - pip:
    - git+https://github.com/casact/chainladder-python/
    - jupyter-book
    - nb_black
