name: cl_latest

channels:
  - defaults
  - conda-forge

dependencies:
  - conda-forge::pandas>=2.0
  - scikit-learn>=0.23
  - sparse>=0.9
  - numba
  - dill
  - patsy
  # testing
  - lxml
  - pytest
  - ipython
  - jinja2
